// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq27Ds_mtFn8RJ2LnxIwLp1ZTGkMuZMxY',
    appId: '1:179788562268:web:2670f8f4256fe588d58b99',
    messagingSenderId: '179788562268',
    projectId: 'salikapp-5',
    authDomain: 'salikapp-5.firebaseapp.com',
    storageBucket: 'salikapp-5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4wFGcZPJVpVS_i5wArV2wO1cmkqLmeOA',
    appId: '1:179788562268:ios:9b1b12af64dea171d58b99',
    messagingSenderId: '179788562268',
    projectId: 'salikapp-5',
    storageBucket: 'salikapp-5.appspot.com',
    iosBundleId: 'com.example.gradApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq27Ds_mtFn8RJ2LnxIwLp1ZTGkMuZMxY',
    appId: '1:179788562268:web:5f6f65f52db2d7a1d58b99',
    messagingSenderId: '179788562268',
    projectId: 'salikapp-5',
    authDomain: 'salikapp-5.firebaseapp.com',
    storageBucket: 'salikapp-5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4wFGcZPJVpVS_i5wArV2wO1cmkqLmeOA',
    appId: '1:179788562268:ios:9b1b12af64dea171d58b99',
    messagingSenderId: '179788562268',
    projectId: 'salikapp-5',
    storageBucket: 'salikapp-5.appspot.com',
    iosBundleId: 'com.example.gradApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc9Ty0Jgr8_gHLPolttHwO7rqudKKFQ2Q',
    appId: '1:179788562268:android:e07468b44f9a645cd58b99',
    messagingSenderId: '179788562268',
    projectId: 'salikapp-5',
    storageBucket: 'salikapp-5.appspot.com',
  );

}